CREATE DATABASE DWBIKE
GO
USE DWBIKE
GO

CREATE TABLE [FACT_ORDER_TRANSACTION](
	[Order_ID] INT PRIMARY KEY,
	[Staff_ID] INT,
	[Customer_ID] INT,
	[Product_ID] INT,
	[Branch_ID] INT,
	[Giftcard_ID] INT,
	[TimeAltKey] INT,
	[DateAltKey] INT,
	[Quantity] INT,
	[Revenue] FLOAT,
	[Discount_Percent] FLOAT,
	[Sale_Tax] FLOAT,
	[Net_Revenue] FLOAT)

GO

CREATE TABLE [FACT_SERVICE_TRANSACTION] (
	[Service_ID] INT PRIMARY KEY,
	[Customer_ID] INT,
	[Service_Type_ID ] INT,
	[Branch_ID] INT,
	[TimeAltKey] INT,
	[DateAltKey] INT,
	[Service_Cost] FLOAT
)  
GO


CREATE TABLE [FACT_PROMOTION_TRACKING](
	[Promotion_ID] INT PRIMARY KEY,
	[Product_ID] INT,
	[Campaign_ID] INT,
	[TimeAltKey] INT,
	[DateAltKey] INT,
	[Unit_Sold] INT,
	[Promotion_Cost] FLOAT,
	[Promotion_Revenue] FLOAT)

GO

CREATE TABLE [DIM_SERVICE_TYPE](
	[Service_Type_ID] INT PRIMARY KEY,
	[Service_Type_Code] NVARCHAR(255),
	[Type_Name] NVARCHAR(255),
	[Type_Detail] NVARCHAR(255)
)

GO

CREATE TABLE [DIM_BRANCH] (
	[Branch_ID] INT PRIMARY KEY,
	[Branch_Code] NVARCHAR(255),
	[Branch_Name] NVARCHAR(255),
	[Phone] NVARCHAR(255),
	[Email] NVARCHAR(255),
	[Street] NVARCHAR(255),
	[City] NVARCHAR(255),
	[State] NVARCHAR(255),
	[Zip_Code] INT
)

GO

CREATE TABLE [DIM_DATE] (
	[DateAltKey] INT PRIMARY KEY,
	[DateKey] INT,
	[Date] DATE,
	[Month] INT,
	[Quarter] INT,
	[Year] INT,
	[Day_Name] NVARCHAR(255),
	[Month_Name] NVARCHAR(255),
	[Day_Of_Week_In_Month] INT,
	[Day_Of_Week_In_Year] INT,
	[Day_Of_Quarter] INT,
	[Day_Of_Month] INT,
	[Day_Of_Year] INT,
	[Week_Of_Month] INT,
	[Week_Of_Quarter] INT,
	[Week_Of_Year] INT,
	[Is_Holiday_USA] BIT
)
GO

CREATE TABLE [DIM_TIME] (
	[TimeAltKey] INT PRIMARY KEY,
	[TimeKey] INT,
	[Time] TIME,
	[Hour_Number] INT,
	[Minute_Number] INT,
	[Second_Number] INT,
	[Time_In_Second] INT,
	[Hourly_Bucket] NVARCHAR(255),
	[Day_Time_Bucket_Group_Key] INT,
	[Day_Time_Bucket] NVARCHAR(255)
)

GO

CREATE TABLE [DIM_MARKETING_CAMPAIGN] (
	[Campaign_ID] INT PRIMARY KEY,
	[Campaign_Code] NVARCHAR(255),
	[Campaign_Name] NVARCHAR(255),
	[Campaign_Type] NVARCHAR(255),
	[Campaign_Budget] FLOAT,
	[Campaign_Channel] NVARCHAR(255)
)
GO

CREATE TABLE [DIM_PRODUCT] (
	[Product_ID] INT PRIMARY KEY,
	[Product_Code] NVARCHAR(255),
	[Product_Name] NVARCHAR(255),
	[Brand_Name] NVARCHAR(255),
	[Category_Name] NVARCHAR(255),
	[Model_Year] INT,
	[List_Price] FLOAT 
)
GO

CREATE TABLE DIM_GIFT_CARD (
	[Giftcard_ID] INT PRIMARY KEY,
	[Gift_Code] NVARCHAR(255),
	[Discount_Percentage] FLOAT,
	[Count] INT
);
GO

CREATE TABLE DIM_CUSTOMER (
	[Customer_ID] INT PRIMARY KEY,
	[Customer_Code] NVARCHAR(255),
	[First_Name] NVARCHAR(255),
	[Last_Name] NVARCHAR(255),
	[Age] INT,
	[Email] NVARCHAR(255),
	[Street] NVARCHAR(255),
	[City] NVARCHAR(255),
	[State] NVARCHAR(255),
	[Zip_Code] NVARCHAR(255)
)
GO

CREATE TABLE DIM_STAFF (
	[Staff_ID] INT PRIMARY KEY,
	[Staff_Code] NVARCHAR(255),
	[Name] NVARCHAR(255),
	[Age] INT,
	[Email] NVARCHAR(255),
	[Phone] NVARCHAR(255)
)
GO

/*
-- Kiểm tra và xóa các khóa ngoại trên bảng FACT_ORDER_TRANSACTION
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Order_Staff')
    ALTER TABLE FACT_ORDER_TRANSACTION DROP CONSTRAINT FK_Order_Staff;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Order_Customer')
    ALTER TABLE FACT_ORDER_TRANSACTION DROP CONSTRAINT FK_Order_Customer;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Order_Product')
    ALTER TABLE FACT_ORDER_TRANSACTION DROP CONSTRAINT FK_Order_Product;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Order_Branch')
	ALTER TABLE FACT_ORDER_TRANSACTION DROP CONSTRAINT FK_Order_Branch;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Order_Giftcard')
    ALTER TABLE FACT_ORDER_TRANSACTION DROP CONSTRAINT FK_Order_Giftcard;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Order_Time')
    ALTER TABLE FACT_ORDER_TRANSACTION DROP CONSTRAINT FK_Order_Time;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Order_Date')
    ALTER TABLE FACT_ORDER_TRANSACTION DROP CONSTRAINT FK_Order_Date;

-- Kiểm tra và xóa các khóa ngoại trên bảng FACT_SERVICE_TRANSACTION
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Service_Customer')
    ALTER TABLE FACT_SERVICE_TRANSACTION DROP CONSTRAINT FK_Service_Customer;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Service_ServiceType')
    ALTER TABLE FACT_SERVICE_TRANSACTION DROP CONSTRAINT FK_Service_ServiceType;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Service_Branch')
	ALTER TABLE FACT_SERVICE_TRANSACTION DROP CONSTRAINT FK_Service_Branch;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Service_Time')
    ALTER TABLE FACT_SERVICE_TRANSACTION DROP CONSTRAINT FK_Service_Time;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Service_Date')
    ALTER TABLE FACT_SERVICE_TRANSACTION DROP CONSTRAINT FK_Service_Date;

-- Kiểm tra và xóa các khóa ngoại trên bảng FACT_PROMOTION_TRACKING
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Promotion_Product')
    ALTER TABLE FACT_PROMOTION_TRACKING DROP CONSTRAINT FK_Promotion_Product;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Promotion_Campaign')
    ALTER TABLE FACT_PROMOTION_TRACKING DROP CONSTRAINT FK_Promotion_Campaign;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Promotion_Time')
    ALTER TABLE FACT_PROMOTION_TRACKING DROP CONSTRAINT FK_Promotion_Time;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK_Promotion_Date')
    ALTER TABLE FACT_PROMOTION_TRACKING DROP CONSTRAINT FK_Promotion_Date;
GO

TRUNCATE TABLE FACT_ORDER_TRANSACTION;
TRUNCATE TABLE FACT_SERVICE_TRANSACTION;
TRUNCATE TABLE FACT_PROMOTION_TRACKING;
TRUNCATE TABLE DIM_SERVICE_TYPE;
TRUNCATE TABLE DIM_BRANCH;
TRUNCATE TABLE DIM_DATE;
TRUNCATE TABLE DIM_TIME;
TRUNCATE TABLE DIM_MARKETING_CAMPAIGN;
TRUNCATE TABLE DIM_PRODUCT;
TRUNCATE TABLE DIM_STAFF;
TRUNCATE TABLE DIM_CUSTOMER;
TRUNCATE TABLE DIM_GIFT_CARD;
*/


