USE DWBIKE
GO
-- Tạo khóa ngoại cho bảng FACT_ORDER_TRANSACTION
ALTER TABLE FACT_ORDER_TRANSACTION
ADD CONSTRAINT FK_Order_Staff FOREIGN KEY (Staff_ID) REFERENCES DIM_STAFF (Staff_ID),
    CONSTRAINT FK_Order_Customer FOREIGN KEY (Customer_ID) REFERENCES DIM_CUSTOMER (Customer_ID),
    CONSTRAINT FK_Order_Product FOREIGN KEY (Product_ID) REFERENCES DIM_PRODUCT (Product_ID),
	CONSTRAINT FK_Order_Branch FOREIGN KEY (Branch_ID) REFERENCES DIM_BRANCH (Branch_ID),
	CONSTRAINT FK_Order_Giftcard FOREIGN KEY (Giftcard_ID) REFERENCES DIM_GIFT_CARD (Giftcard_ID),
	CONSTRAINT FK_Order_Time FOREIGN KEY (TimeAltKey) REFERENCES DIM_TIME (TimeAltKey),
	CONSTRAINT FK_Order_Date FOREIGN KEY (DateAltKey) REFERENCES DIM_DATE (DateAltKey);

-- Tạo khóa ngoại cho bảng FACT_SERVICE_TRANSACTION
ALTER TABLE FACT_SERVICE_TRANSACTION
ADD CONSTRAINT FK_Service_Customer FOREIGN KEY (Customer_ID) REFERENCES DIM_CUSTOMER (Customer_ID),
	CONSTRAINT FK_Service_ServiceType FOREIGN KEY (Service_Type_ID) REFERENCES DIM_SERVICE_TYPE (Service_Type_ID),
	CONSTRAINT FK_Service_Branch FOREIGN KEY (Branch_ID) REFERENCES DIM_BRANCH (Branch_ID),
	CONSTRAINT FK_Service_Time FOREIGN KEY (TimeAltKey) REFERENCES DIM_TIME (TimeAltKey),
	CONSTRAINT FK_Service_Date FOREIGN KEY (DateAltKey) REFERENCES DIM_DATE (DateAltKey);

-- Tạo khóa ngoại cho bảng FACT_PROMOTION_TRACKING
ALTER TABLE FACT_PROMOTION_TRACKING
ADD CONSTRAINT FK_Promotion_Product FOREIGN KEY (Product_ID) REFERENCES DIM_PRODUCT (Product_ID),
	CONSTRAINT FK_Promotion_Campaign FOREIGN KEY (Campaign_ID) REFERENCES DIM_MARKETING_CAMPAIGN (Campaign_ID),
	CONSTRAINT FK_Promotion_Time FOREIGN KEY (TimeAltKey) REFERENCES DIM_TIME (TimeAltKey),
	CONSTRAINT FK_Promotion_Date FOREIGN KEY (DateAltKey) REFERENCES DIM_DATE (DateAltKey);